language: csharp
mono: none
dotnet: 2.2.104
solution: Mariowski.Common.sln
dist: xenial

install:
- dotnet restore

script:
- dotnet build -c Release
- dotnet test -c Release
- dotnet pack -c Release

deploy:
  skip_cleanup: true
  - provider: script
    script: dotnet nuget push src/Mariowski.Common/bin/Release/Mariowski.Common.*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+
  - provider: script
    script: dotnet nuget push src/Mariowski.Common.DataSource/bin/Release/Mariowski.Common.DataSource.*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^ds-[0-9]+\.[0-9]+\.[0-9]+